### ISSUE TITLE
make one thing to import when making usual bots

### ISSUE THREAD

**Issue by miselico** [intelligent-systems-course/schnapsen#13]
In the final platform, there should be only one import statement needed to import all things that are usually needed to create bots.
So, GameState, cards, suits rank, and the different kinds of moves should be collected into one packagem which might just be `schnapsen`

**Comment by tae898** [comment]
Assignee: Nikos

**Comment by miselico** [comment]
This is more or less the case. Most parts are in schnapsen.game, some in schnapsen.deck
