### ISSUE TITLE
Some form of the platform is needed in intelligent systems course

### ISSUE THREAD

**Issue by miselico** [intelligent-systems-course/schnapsen#2]
There are 6 exercises

## Exercise 1-2:
* data: start Novemeber
* Simplified game - 1 player variant?
   * Need to be completed
* BFS/DFS - only in the notebooks
* No need for the game engine itself

## Exercise 3
* date: second half of November??
* 2 bots play against each other
* Random bot vs. rdeep vs. bullybot

## Exercise 4
* Knowledge based bot and ML bot

## Exercise 5 and 6
* tournaments are used

# Improving assignments

* Knowing what to do is the hardest
* Crashing local jupyter server

**Comment by tae898** [comment]
@miselico 
Nikos: What do you mean by the platform here? Can you be more specific?

**Comment by miselico** [comment]
the current platform can do these.
